### ISSUE TITLE
Re-write metagenome_contributions.py

### ISSUE THREAD

**Issue by gavinmdouglas** [picrust/picrust2#1]
```metagenome_contributions.py``` no longer in this repository - there could be better way to output the contributions that could leverage the likelihoods outputted in R by the discrete hidden-state prediction methods.

**Comment by gavinmdouglas** [comment]
```metagenome_pipeline.py``` outputs functions stratified by functional contributions by default now. ```per_sample_functions.py``` is still **experimental** script to use probability distributions rather than discrete predictions.

**Comment by jjmmii** [comment]
Hi @gavinmdouglas , I updated the local clone today and noticed that metagenome_pipeline.py is taking a long time to run (job has been running for 8 hours and still running). I guess it's because it's calculating stratified output? Is there a way to turn off this option? Thank you so much.

Best,
-Jamie

**Comment by jjmmii** [comment]
Thanks so much Gavin! It is blazing fast now :)

**Comment by jjmmii** [comment]
Just to follow-up, the latest clone of PICRUSt2 as of yesterday did not have this problem.
