### ISSUE TITLE
pandas to_csv compression "infer" mode is not working 

### ISSUE THREAD

**Issue by amirshams84** [picrust/picrust2#114]
Hi,
having the following error
`ValueError: Unrecognized compression type: infer`
I edited hsp.py and metagenome_pipeline.py changed "infer" to "gzip"
and it is working

**Comment by gavinmdouglas** [comment]
Hi @amirshams84, what versions of pandas and picrust2 do you have installed? And how did you install the tool? Incompatibilities like this shouldn't come up if the versions are within the ranges specified in the conda recipe.

**Comment by amirshams84** [comment]
I use your conda to install picrust2
`conda create -n picrust2 -c bioconda -c conda-forge picrust2=2.3.0_b`
I am not sure if the panda version upgrade get superseded by other environments or not, 
it would be great if you can clarify which version of pandas you have used

Thanks
By the way great tools

**Comment by gavinmdouglas** [comment]
Thanks!

The package versions listed in https://github.com/picrust/picrust2/blob/master/picrust2-env.yaml should all work.

**Comment by amirshams84** [comment]
the version I have is 0.23.4, 
so maybe we should assert that during building conda environment
`conda create -n picrust2 -c bioconda -c conda-forge -c anaconda picrust2=2.3.0_b pandas=0.24.2`
Regards

**Comment by gavinmdouglas** [comment]
Thanks for the info - that shouldn't be necessary actually because that's already specified in the conda recipe. You can see what's specified in the conda recipe here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/picrust2/meta.yaml

I think there may be another python being specified earlier in your PATH variable or interference from another environment that is causing this problem.

Gavin

**Comment by amirshams84** [comment]
thanks
close

**Comment by amirshams84** [comment]
Thanks
