### ISSUE TITLE
List of mapped species

### ISSUE THREAD

**Issue by kunstner** [picrust/picrust2#115]
Hi, 

I'm wondering whether it is possible to retrieve the actual name of the species that it's inferring genomic content from to pull KEGG elements from? 

Best,
 Axel

**Comment by gavinmdouglas** [comment]
Hi @kunstner, the genomic content isn't pulled from individual species' genomes so it would be hard to do that. Also, the reference files contain the IMG genome ids but currently there isn't a mapping available between these reference ids and species names (you can probably find such a mapping on the KEGG website though). If you wanted to pull info from individual genomes you could potentially just do a similarity match against each reference 16S sequence rather than using PICRUSt2 (which infers functions based on a phylogenetic approach).

**Comment by kunstner** [comment]
Hi @gavinmdouglas 
thanks for your reply. I was already thinking that it is not possible to get this information (as far as I understood the algorithm).
Best,
 Axel
