### ISSUE TITLE
Error while running picrust2_pipeline.py (place_seqs.py)

### ISSUE THREAD

**Issue by Aliceall** [picrust/picrust2#117]
Hi @gavinmdouglas,
I have installed picrust2 with conda following your instructions, and it worked fine until now. I have now reinstalled it three or four times, from source, or with conda, but I can't figure out what is wrong. I have picrust2=2.3.0_b now installed within a conda env on a machine running Ubuntu 18.04, with a ram of 20 GB. It would seem that when trying to align my sequences to the reference it does not find any similarity, but I am not sure why, I used before this fasta file and seemed to work fine . 
Any help is really appreciated! 
Thank you again
This is the error I get:
(picrust2) giada@giada-VirtualBox:/media/sf_sf/ML$ picrust2_pipeline.py -s rep-seqs_full.fna -i seqtab-biom-table.biom -o picrust2 --stratified --per_sequence_contrib

Error running this command:
place_seqs.py --study_fasta rep-seqs_full.fna --ref_dir /home/giada/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust2/out.tre --processes 1 --intermediate picrust2/intermediate/place_seqs --min_align 0.8 --chunk_size 5000

Standard error of the above failed command:
Stopping - all 2201 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).

**Comment by Rachael-16** [comment]
I'm having the same problem on a HPC cluster as well.

**Comment by gavinmdouglas** [comment]
Hi @Aliceall and @Rachael-16,

I added an extra check in the last release to make sure all input sequences align to the reference sequences by at least 80% and your sequences are being thrown out because they are below this cut-off. You can see the alignment of your query sequences against the reference sequences in `intermediate/place_seqs/study_seqs_hmmalign.fasta`. If they are only partially aligning, but at a reasonable length, then you could decrease the `--min_align` setting. If it looks like they aren't aligning at all then there must be something else going on with the input data.


Best,

Gavin

**Comment by Aliceall** [comment]
Thank you Gavin for the quick response!
I don't have that file, the only file generated is the following: query_align.stockholm
I will try again.
Thanks
Giada

**Comment by Aliceall** [comment]
I was able to open with text editor, and the sequences are not very well aligned. Even when decreasing to 0.5. I will try with a dataset that worked before now.

**Comment by gavinmdouglas** [comment]
Hi again,

Thanks a lot for posting this issue. It made me realize that if users input sequences that don't align at all to the reference alignment prior to v2.3.0-b then predictions would still be output unfortunately (and not be useful at all unfortunately). This issue happens, because for some reason really poorly aligning sequences can sometimes be placed with high confidence close to the tips of the tree by EPA-ng (at least with the default reference tree).

Screening out these problematic sequences in advance should help avoid this problem, but unfortunately this means that the first time you ran the data through it probably just output random predictions.

I made a post to the google group here: https://groups.google.com/forum/#!topic/picrust-users/PMT1i3e80dY to let everyone know and sorry for the inconvenience.


I'm not sure why your particular input sequences aren't aligning - could you send me a few example sequences to look at?

**Comment by Aliceall** [comment]
Thank you Gavin.
I understand. I processed the data with dada2 pipeline, classified with gg2013...the otu table looked good to me, but clearly something is happening. I am going to send you both the query_align.stockholm and the original table, if you want to take a look. 
Thank you again!
Giada

**Comment by gavinmdouglas** [comment]
Hi @Aliceall,

It looks like your sequences are on the negative strand which is why they aren't being aligned properly. If you take the reverse complement of your input data it should work.


Best,

Gavin

**Comment by Aliceall** [comment]
Ah! Thank you very much!! I feel dumb. dada2 try the rc automatically at assignment but when I exported the tables I did it from the dada2 object created before. 
I added now a step of rc and then exported and it works, and excluding the few sequences that did not align properly. 
Thank you again!

**Comment by gavinmdouglas** [comment]
Good to hear!

**Comment by eperezv** [comment]
I faced the same issue and thanks that I found this issue. Maybe a warning (along with the error message) could help people like me. 

Thanks

**Comment by gavinmdouglas** [comment]
Thanks for the suggestion @eperezv, I'll add that into the next release.

**Comment by zoelwl** [comment]
> Thank you Gavin. I understand. I processed the data with dada2 pipeline, classified with gg2013...the otu table looked good to me, but clearly something is happening. I am going to send you both the query_align.stockholm and the original table, if you want to take a look. Thank you again! Giada

**Comment by zoelwl** [comment]
Hi @Aliceall, i want to know what step are you added. Because i have same question.
