### ISSUE TITLE
Biom file does not match with fasta file 

### ISSUE THREAD

**Issue by EnuhBlaise** [picrust/picrust2#118]
Greetings to all.. 
I AM trying to do a picrust analysis, I found out my biom file sequences are not arranged to match the greengenes format. I had generated the biom file with qiime.  What do I do? Should I do another pipeline with mothur or there is a way to fix the biom file. 

Also, I have 6GB ram, does it mean picrust pipeline will not run at all or it will take a longer time

**Comment by gavinmdouglas** [comment]
Hi @EnuhBlaise,

PICRUSt2 is compatible with any 16S sequence input (i.e. ASVs or database OTUs). 6 GB of RAM probably isn't enough to run the default pipeline, because the default placement step takes more memory. You could try placing your ASVs with SEPP with the QIIME 2 plugin though as described here: https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial.

If that doesn't work for you then there are also other metagenome prediction tools like Piphillin and Tax4Fun2, which have lower computational requirements.


Best,

Gavin
