### ISSUE TITLE
Discrepancies in 16S copy numbers

### ISSUE THREAD

**Issue by eperezv** [picrust/picrust2#121]
Hello,

I am using picrust2 to calculate the 16S copy number and (potentially) correct my OTU table. I've been able to successfully run the pipeline but faced important concerns when looking at detail on the data. In particular, I was surprised that many sequences identified as genus, which should have a high number of copies (such as Burkholderia that on rrndb have ca. 4), had 1 copy. The NSTI was generally <0.1, with many cases even <0.01 and only one copy, so I guess the problem (if any) comes from the database. This happened with several genera.

When comparing with the metagenomic sequencing, the composition after correcting was even more different than those before correcting. I guess the copy number of some bacteria is not properly being estimated. Maybe because of the reference?

Is it possible to easily use another database (such as rrndb) with picrust2?

**Comment by gavinmdouglas** [comment]
Hey @eperezv,

The 16S copy numbers in the reference database are just based off of how many copies are found in each IMG genome. These numbers can be inaccurate if 16S copies are missing from the assembly. I looked into it and there are many Burkholderia genomes which have just 1 based on this approach, but most have 3-5. In addition, the prediction of any function will be dependent on how well the input sequences are placed in the reference tree - it's possible if the sequences are placed in the wrong place then the prediction could be wrong just because of that.

In my experience the Spearman correlation with metagenomics data is not affected much by whether 16S copy number correction is done or not, but it's interesting to know that it did have an effect in your dataset!

I don't have a file that links IMG genomes to the rrndb database, but if you wanted to link IMG genome ids to this database then you could certainly point to a different 16S copy number reference file when running PICRUSt2!

**Comment by gavinmdouglas** [comment]
I also would have expected a higher correlation - thanks for sharing this result.

I don't have a script to do this, but you could definitely subset the reference files to the subset of genomes that you're interested in. You would also need to prune the reference tree to just the tips you're interested in, which could be done with the `drop.tip` function in the `ape` R package. 

The default reference files are in `picrust2/default_files/prokaryotic` (the files for the `place_seqs.py` command are in the `pro_ref` subdirectory).

**Comment by eperezv** [comment]
Ok. I will try out.
I thought it was more difficult because of some files (models) that I saw in the folder.

**Comment by gavinmdouglas** [comment]
You may have to re-generate the model and hmm files, I'm not sure if they will work if the other reference files are subsetted - you can see a description here: https://github.com/picrust/picrust2/wiki/Sequence-placement#using-custom-reference-files

**Comment by eperezv** [comment]
I made it. The predicted values seem now more realistic.
By the way, I have been re-checking my previous calculations and I made a mistake. The number of matching taxa is around 6.600 and r=0.43. A bit better ;)
