### ISSUE TITLE
EC mapping of EC7.x.x.x missing? 

### ISSUE THREAD

**Issue by swidder** [picrust/picrust2#128]
Hi, 
I was searching for particular EC numbers in the default mapping files and it seems as if no EC numbers of the translocases domain existed (e.g. metacyc_pathways_structured_filtered). These are classified as EC 7.x.x.x. The same is true for the  description files (metacyc_pathways_info.txt). Is there any particular reason? These functions are on the other hand present in KEGG/KO mapping files. I would like to better understand likely transport processes in my biom using metacyc- do you have any suggestions how to proceed? 
Thanks,
Stefanie

**Comment by gavinmdouglas** [comment]
Hi @swidder,

Do you know the exact MetaCyc pathway ids that you're interested in? It's possible that the matching pathway between KEGG and MetaCyc may not be defined. However, it could be defined and be missing because many pathways were filtered out of those files due to being based on a low number of reactions (so they were deemed to not be able to be reliably predicted). This set of pathways was chosen to match HUMAnN2's output set.

**Comment by swidder** [comment]
Thank you for your response.
I am particularly interested in ABC transporters and other transport types that connect prokaryotes with the environment. 
To be more comprehensive though, I conducted a query on metacyc for reactions with parent class 'transporter‘ and recorded common name, EC number and metacyc frameID. These include ECs with domain 7 (the ones that are entirely missing from the mapping file), but also others involved in transport systems, which I didnt check for presence in the mapping.
I attach the file to this email.
Many thanks, 
Stefanie

**Comment by gavinmdouglas** [comment]
Hi @swidder,

I don't see any attachment - would you mind re-sending it?


Gavin

**Comment by swidder** [comment]
Hi,
Did the attachment come along now?
Best
Stefanie

**Comment by gavinmdouglas** [comment]
No actually - I think you need to actually attach it on the GitHub website.

**Comment by swidder** [comment]
[transport_reactions_metacyc.txt](https://github.com/picrust/picrust2/files/4937685/transport_reactions_metacyc.txt)

FYI it is a .tsv file, but github requires .txt - sorry for the inconvenience!

**Comment by gavinmdouglas** [comment]
Thanks for sending the file - it looks like those reactions were excluded from the mapfile at some point in HUMAnN2 (which are the same mapfiles I used for PICRUSt2). I'm not totally sure why, but it looks like the reactions were lost after the pathway mapfile was converted to "structured" format (i.e. allowing for the and/or syntax of pathways rather than just all reactions contributing equally). One solution might be to focus your analysis on the specific EC numbers themselves that you're interested in rather than looking at the pathway level.

Best,

Gavin

**Comment by swidder** [comment]
Hi,
Yes I agree. I also think it is the straight-forward way to proceed via EC numbers. 
But perhaps I could suggest that there should be some note added to the picrust2 documentation that transport reactions are excluded systematically. 
Thanks for your support and the great tool,
Stefanie
