### ISSUE TITLE
Custom Database: SILVA 138.1

### ISSUE THREAD

**Issue by beatrizrb** [picrust/picrust2#142]
Greetings guys!

I'm very new to PICRUSt2 so apologies if this question is basic.

I need to use SILVA as the database in PICRUSt2, so I started making the directory that PICRUSt2 says its necessary for custom databases (https://github.com/picrust/picrust2/wiki/Sequence-placement).

But I'm having a hard time trying to create the modelfile (extension .model). I tried to follow the instructions present in this link (https://github.com/Pbdas/epa-ng#setting-the-model-parameters) but I'm getting a lot of errors with the raxml command:

raxml-ng --evaluate --msa pro_ref.fna --tree pro_ref.tre --prefix info --model GTR+G+F  

Files that I'm using:
- SILVA_138.1_SSURef_tax_silva_full_align_trunc.fasta.gz as pro_ref.fna
- tax_slv_ssu_138.1.tre.gz as pro_ref.tre
(both files are available in https://www.arb-silva.de/no_cache/download/archive/release_138_1/Exports/)

If anyone can help me, I'll be very very grateful. 

Thank you in advance

**Comment by Pbdas** [comment]
Hi @beatrizrb,

not sure if your problem is still relevant given the time since it was posted, but maybe I can help.

The tree that you're trying to evaluate is a (heavily) multifurcating taxonomy, not a phylogenetic tree. What `raxml-ng --evaluate` expects is a fully resolved tree. So one way to solve that is to instead run a proper treesearch, perhaps with the taxonomy as a constraining tree (raxml will then try to find the most likely tree that doesn't conflict with the tree you've specified).

Whether that makes sense is debatable, depending on how much you trust the SILVA taxonomy, but also how much you think you can trust an all-database tree. On top of that it would take a lot of compute to resolve such a large tree, and you may not be satisfied with the result. Perhaps this would be a better approach: https://academic.oup.com/bioinformatics/article/35/7/1151/5088318
That paper should do almost exactly what you want to do, if I get your goals correctly. Using a smaller/more compact tree will make everything a lot faster, less memory hungry, and rid you of any illusion of being able to distinguish down to the species level.

Pierre
