### ISSUE TITLE
Picrust2 outputs

### ISSUE THREAD

**Issue by carolynePearl** [picrust/picrust2#144]
I was able to successfully run picrust2 using the qiime plugin i have two questions;

1. I have obtained the three outputs; ec output, ko_output and the pathways_output; moving forward to down stream analysis; can i proceed analysis with the pathways file only? In your analysis, what do you use the other two files for?

2. Lastly; do you have a downstream analysis vignette i can use? probably in R (not STAMP). That would be helpful for further analysis.

**Comment by gavinmdouglas** [comment]
Hey @carolynePearl,

1. I personally mainly analyze the KO outputs, because I have less confidence in pathway predictions (you can see them each validated in the PICRUSt2 paper). However, a lot of researchers are more interested in pathway data because there are fewer features and they have clearer interpretations.

2. Related to the above point - there is no single recommended analysis pipeline. I think it is an open question regarding how to reproducibly analyze functional microbiome data in general and so I am concerned that different differential abundance tools can often return quite different results and it's unclear which is most correct. You can see examples of this in our manuscript where the performance of different tools on even metagenomics data processed through an alternative processing pipeline resulted in starkly different significant functions. If you're interested in differential abundance testing then I think the best way to proceed would be to run multiple tools and take the intersect of significant hits.


Hopefully that helps!

Gavin
