### ISSUE TITLE
pytest error

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#149]
Good day!

I am quite new to picrust2 and have already encountered a problem after installation.

When I tried running pytest, the error I get is:

_ ERROR collecting cmake-3.13.0-rc1/Tests/PythonCoverage/coveragetest/test_foo.py _
import file mismatch:
imported module 'test_foo' has this __file__ attribute:
  /home/ryan/cmake-3.13.0-rc1/Testing/PythonCoverage/coveragetest/test_foo.py
which is not the same as the test file we want to collect:
  /home/ryan/cmake-3.13.0-rc1/Tests/PythonCoverage/coveragetest/test_foo.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules

I am unsure how I could follow the HINT.

Thanks a lot!

**Comment by gavinmdouglas** [comment]
Hey @carlmed00,

The issue is that `pytest` automatically tries to run all python scripts beginning with "test" in the directory where the command is run and then all subfolders recursively.You can see that the script being referred to is actually for an unrelated tool (cmake).

When install picrust2 from source it is intended that the user run this in the picrust2 folder. If you installed the tool with bioconda then you don't need to run this command.

Cheers,

Gavin
