### ISSUE TITLE
convert_table.py not generating percent contributions

### ISSUE THREAD

**Issue by alisongomeiz** [picrust/picrust2#164]
Hi there,

I have successfully generated stratified outputs through the `picrust_pipeline.py` script and wanted to generate the "legacy format" as provided by the `convert_table.py` function. However, when I do this, I get an output with six columns:

Gene Sample OTU OTUAbundanceInSample GeneCountPerGenome CountContributedByOTU

It looks like there's a way to add two additional columns at the end of this: "ContributionPercentOfSample" and "ContributionPercentOfAllSamples". Is there a flag that I am missing in order to generate these values, or even a manual way to add them? I am attempting to visualize my results in R (ggplot2) but am running into issues without the percentages.

**Comment by gavinmdouglas** [comment]
Hey @alisongomeiz,

No sorry there isn't a flag to generate those values. The issue is actually that I'm not entirely sure how those columns were calculated in PICRUSt1 and I think they caused confusion so I decided to leave them out. However, you could get the percentages in each sample with R using commands like the ones listed on this page: https://bookdown.org/marius_mather/Rad/tidyverse.html . If you go down to section 7.2.3 on that page and look at how to calculate percentages of a column in conjunction with the `group_by` command I believe that will do what you need,


Cheers,

Gavin

**Comment by diegoibt** [comment]
Hi Gavin

Hope you are doing great!, those columns are needed to display the data in BURRITO (http://borenstein-lab.github.io/burrito/data_input.html#function) right?, Actually for me is a big issue since I cannot visualize my data because of those missing columns. 

Thank you in advance

Diego

**Comment by gavinmdouglas** [comment]
Hi @diegoibt,

Thanks for letting me know - I didn't realize those columns were necessary. I'll add them in for the next release once I'm sure of how they were calculated in PICRUSt1.


Cheers,

Gavin

**Comment by alisongomeiz** [comment]
Hi @diegoibt,

I actually just closed out an issue with one of the developers over at the BURRITO GitHub page about that issue. Apparently the last two columns are not actually needed for the analysis of the pipeline (even though they say it's required). I was able to generate an output from BURRITO just fine with just the six columns. 

I do think that other programs like MIMOSA still do require the last two columns, so I think it's still worth adding those outputs in the next release, @gavinmdouglas. In any case, it's nice to have if I want to move over to Excel or R to visualize data as percentages.

Regards,
Alison

**Comment by diegoibt** [comment]
Hi @alisongomeiz 

That was awesome! Since I cannot visualize my data from picrust2 with BURRITO, how they explained this?, because when I try to visualize in the last week, their server dropped me out.. all days, all time, and moreover I could not find any branch to add my issue at their github. How do you perform this request?

Thank you in advance

Diego

**Comment by alisongomeiz** [comment]
Diego:

I have also found that the server drops out sometimes. If you [open an issue](https://github.com/borenstein-lab/burrito/issues) over at their GitHub page, sometimes there's something they can fix on their end when the website is down. I have alerted them to this in the past, and by the next day it was fixed and I used it successfully.

That link should take you to their issues page where you can open an issue if you need.

-Alison
