### ISSUE TITLE
issues with generated legacy contrib file

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#167]
Hello!

I have been trying to use Burrito to visualize my Picrust2 data. However, analysis does not proceed since my contrib table seems to follow the column sequence required by Burrito (sample column being the second). The contrib.legacy one does rearrange that, however, there are less columns that Burrito doesn't identify it  as a proper contrib table.

I cannot manually switch this columns, however, since excel does not load the entire file. Any insights or something I must do or must be missing?

Thanks!

**Comment by carlmed00** [comment]
I have seen a threat regarding this saying that apparently the last two column isn't needed. However, I just observed that it seems like the columns being converted to legacy aren't the counts but the relative abundances. Wouldn't this lead to an incorrect analysis?

**Comment by gavinmdouglas** [comment]
Hey @carlmed00,

For converting to the legacy format you can specify `--raw_abun` if you want counts rather than relative abundances to be output. As BURRITO focuses on stacked bar charts of relative abundance I think either would be fine though, but you can compare if you suspect it's a problem.

I'm adding the "ContributionPercentOfSample" to the output in the next release, but not the other column because I think it causes too much confusion and is misleading. 

Does that answer your question?

Thanks,

Gavin

**Comment by carlmed00** [comment]
> Hey @carlmed00,
> 
> For converting to the legacy format you can specify `--raw_abun` if you want counts rather than relative abundances to be output. As BURRITO focuses on stacked bar charts of relative abundance I think either would be fine though, but you can compare if you suspect it's a problem.
> 
> I'm adding the "ContributionPercentOfSample" to the output in the next release, but not the other column because I think it causes too much confusion and is misleading.
> 
> Does that answer your question?
> 
> Thanks,
> 
> Gavin

Cool!! Yes it answers my question. Thank you!

By any chance, is there an estimated date for the next release?

Thank you very much again!

**Comment by gavinmdouglas** [comment]
Ok good to hear - I'm hoping to make the release this or next week.
