### ISSUE TITLE
Compatibilities issues

### ISSUE THREAD

**Issue by ElifKardas** [picrust/picrust2#174]
The HPCF system programmer tried to install PICRUST2 on the cluster of my university from source because conda never managed to find the package in its repos. He used this: https://github.com/picrust/picrust2/wiki/installation . 

The version installed is 2.4.1. The pip version he used is: 
```
# ./pip --version
pip 21.0.1 from /cm/shared/apps/qiime2/2021.2/envs/qiime2-2021.2/lib/python3.6/site-packages/pip (python 3.6)
```
However, running "pytest" afterward produces some failed tests that seem to be the product of compatibility issues. Some of the errors of the failed test say:
> FileNotFoundError: [Errno 2] No such file or directory: 'epa-ng': 'epa-ng'
others say:
> Error when running glpsol from MinPath

Pytest does result in more passed tests than failed ones:
> "19 failed, 42 passed in 130.57s (0:02:10)"

When I run my command line. It does not work, "plugin picrust2 not present"

Any help would be appreciated. 

Thanks,

**Comment by gavinmdouglas** [comment]
Hi @ElifKardas,

These errors do make it seem like the installation didn't complete correctly. This might be because even when you install from source it needs to use conda to download the prerequisites. Were there any errors upon running `conda env create -f  picrust2-env.yaml`? 

You might want to try updating to the latest version of conda to see if that fixes the problem. Also, sometimes you just need to let conda search for packages for a really long time - that's a known issue with conda that comes up from time to time and I haven't personally figured out how to avoid that.


Cheers,

Gavin
