### ISSUE TITLE
PICRUSt2 Tutorial

### ISSUE THREAD

**Issue by EzyTay** [picrust/picrust2#185]
Hi there,

I tried to follow the PICRUSt2 Tutorial and I can't seem to even complete step 1: 
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/chemerin_16S.zip
unzip chemerin_16S.zip
cd chemerin_16S

It shows error 404 not found. Wondering if it's my issue or if the file is no longer available for download? 

Thanks in advance.

**Comment by gavinmdouglas** [comment]
Ah it looks like that public files on that server were re-organized - I fixed the link and it can now be found here: `http://kronos.pharmacology.dal.ca/public_files/picrust/picrust2_tutorial_files/chemerin_16S.zip`. 


Thanks for pointing this out!

**Comment by edmundtayzy** [comment]
Hi Gavin,

Thanks for your prompt reply. I was able to download it and unzip it! Now I'm having some other issue with the subsequent steps, I have tried to google it but there was no one that seems to be able to give a clear and direct instruction/ explanation of what the issues are. (I am still fairly new to this area so thus the lack of knowledge, apologies in advance!)

When I place reads into reference tree (place_seqs.py -s ../seqs.fna -o out.tre -p 1 \
              --intermediate intermediate/place_seqs)
 I get the following message: 
 
 epa-ng --tree /home/tayezy/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa intermediate/place_seqs/ref_seqs_hmmalign.fasta --query intermediate/place_seqs/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/tayezy/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w intermediate/place_seqs/epa_out --filter-acc-lwr 0.99 --filter-max 100
 
 And also, subsequently, if I try to run the next step on my Mac terminal, it shows that castor package is not found but on my other laptop using Linux terminal I didn't get the message for castor package not found (instead it was out.tre not found - figured prob due to the previous step) 
 
 The thing is, I downloaded miniconda3/picrust the same way for both of my laptops so I don't really know why my Mac is showing castor package not found. 
 
Apologies and thanks in advance! Appreciate it!

**Comment by gavinmdouglas** [comment]
Hi there,

Sorry I'm confused about what the issue is here - are you saying you're having different issues on two different computers?

Regarding  the epa-ng message: in of itself that doesn't mean that it's an error, that's simply the command being run. However, if no output is produced then likely you're running into issues due to memory limitations (you need ~16 GB of RAM at least) to run EPA-ng. You can use the sepp placement option instead to get around that.

Regarding castor not being present - are you getting a similar error as reported here? https://github.com/picrust/picrust2/issues/143


Cheers,

Gavin

**Comment by gavinmdouglas** [comment]
You could try re-installing castor manually as a first pass. I.e., in the environment start R and then just install castor with ```install.packages```.

**Comment by edmundtayzy** [comment]
Hi Gavin,

Thanks for your help. I have managed to download castor manually on my Mac and was able to follow through the tutorial without any issues! 

I have another windows laptop that I'm planning to do my main analysis work on. The thing is that with my Linux sub system (Ubuntu) I am unable to set the RAM to ~16GB, i will try the sepp placement option and will let you know again! 

Thank you so much!
