### ISSUE TITLE
Representation of environments

### ISSUE THREAD

**Issue by ARW-UBT** [picrust/picrust2#207]
Hello, 
You mentioned in the 'Key Limitations' section of this Picrust2 Wiki that 'certain environments are better represented by reference genomes than others'. Our 16S data came from freshwater microbiomes, and I am wondering whether you have any experience, how good such environmental metagenomes will be recognized by Picrust2? 
I have analyzed the your sample data from the tutorial (mammal_biom.qza) and found that there are 371 ASVs which result in 2,241 EC features (roughly 8 EC features per ASV). If I compare it to our dataset from natural freshwater, I used 1,794 ASVs which result in only 2,003 EC features, respectively. Much less feature per ASV!
Is there a possibility that metagenomes from natural environments are less well included in the Picrust2 database? 

Is there a possibility to visualize whether environmental metagenomes are generally less well represented in the funtional database, or whether there is an 'assymetric' drop of annotation (few tax with good representation, many taxa with no functional representation)?

I used the Qiime2 Picrust2 plugin for the analyses. 

Best regards

**Comment by gavinmdouglas** [comment]
It's very likely that there are fewer 16S sequences in the default database that correspond to reference genomes from freshwater sources compared with reference genomes from mammalian stool. The analysis that you're describing is a little tricky as the only metrics that are provided are related to how well the 16S sequences are placed in the reference phylogeny (i.e., the NSTI values, which can be produced if you run the standalone version). But this can be misleading as even if the 16S sequences perfect matches for those in the database that is no guarantee that the genome content is very similar, due to extensive pangenome variation within prokaryotic species.

We identified very similar ranges of Spearman correlations between predicted and metagenomics-inferred functions across a range of environments (as shown in Fig 2 of the paper), so I can say that the coarse high-level predictions are likely better than random for this environment, but I would be very cautious in terms of how you report findings based on individual functions as those could very easily be false positives / negatives.


Hopefully that helps!

Gavin
