### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Felix-Matheri** [picrust/picrust2#209]
Dear Gavin (and team),

Many thanks for this elaborate tutorial.we have run the pipeline obtaining stratified and unstratified outputs of Pathways, KO, and Enzymes.

We are stuck at this point and arent seeing options visualize the results. Looking forward

**Comment by gavinmdouglas** [comment]
Hey @Felix-Matheri,

There aren't specific visualization options that we provide unfortunately.

I would recommend reading the data into a python or R environment and making custom plots if that's possible.

Otherwise you can try visualizing the unstratified data with STAMP, as described here: https://github.com/picrust/picrust2/wiki/STAMP-example

BURRITO is one tool that can visualize taxa-stratified function tables.


Hopefully that helps!

Gavin

**Comment by Dnman-code** [comment]
Hi Felix, could you share the code you used to create the stratified files you analysed later in R? Thanks in advance.
