### ISSUE TITLE
Several modules in "KEGG_modules_to_KO.tsv" have no descriptions

### ISSUE THREAD

**Issue by wangpeng407** [picrust/picrust2#222]
Hi, thanks for offering picrust2.

I found that some modules in ```default_files/pathway_mapfiles/KEGG_modules_to_KO.tsv``` have no corresponding descriptions in ```KEGG_modules_info.tsv.gz```, even in [official KEGG website](http://rest.kegg.jp/list/module), such as M00237, M00221, M00194, M00197...... 

Running ```add_descriptions.py``` will assign these modules not_found.

So my question is how to search the information of these modules according to IDs.

**Comment by gavinmdouglas** [comment]
Hi @wangpeng407,

I think this is coming up because the KO to modules mapping file is from the last open-source version of KEGG (which was packaged with HUMAnN2). I think some modules must subsequently have been removed from KEGG since for instance I can't find M00237 when I search for it on the KEGG website here: https://www.genome.jp/entry/M00237. I'm not sure how reliable this website is, but you can see that at least one point this module had annotation info which you can see here: https://bio2rdf.org/describe/?url=http%3A%2F%2Fbio2rdf.org%2Fkegg%3AM00237


Sorry for the confusion!

Gavin

**Comment by wangpeng407** [comment]
Very appreciated @gavinmdouglas 
I got the source file. it's [here](https://github.com/biobakery/humann/blob/master/humann/data/misc/map_kegg-mdl_name.txt.gz). But I still don't know if it's appropriate for publication, because these modules have no details in KEGG.

**Comment by gavinmdouglas** [comment]
Yes I can see that's annoying. You can actually acquire the latest KEGG mapping files for free through their API if it's for academic work (but I don't believe I'm allowed to distribute them with the PICRUSt2 repo).

For instance to download the mapping of KOs to modules you could run: 
```
wget http://rest.kegg.jp/link/module/ko
```

And to get the descriptions of KEGG modules:
```
wget http://rest.kegg.jp/list/module
```
