### ISSUE TITLE
find ASVs' weights for each pathway

### ISSUE THREAD

**Issue by g-antonello** [picrust/picrust2#243]
Dear all,
Thank you for this cool tool, especially since you made it so much easier to play with ;) 
I am rather new, so be patient in case it is already there, but I was wondering where I could have some statistics regarding how much an ASV contributes to each final pathway abundance. 
I'm thinking about a table with ASVs in rows, first 2 columns the nsti statistics (n° 16S genes and distance from closest metagenome) and then all pathway in the final output with the weights it has on the pathway output results. 
or even just a 0 to 1 "completeness of pathway in the genome" score.

Is this resource already available? And do you think it would be of interest?

All the best,
Giacomo

**Comment by gavinmdouglas** [comment]
Hey Giacomo,

Thanks for sharing your thoughts! It sounds like what you're describing is quite similar to the stratified output (i.e., when the `--strat_out` option is used). Is that not the case?


E.g., for the gene family level the stratified output is described in the tutorial, but it's very similar for the pathway level predictions: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.4.2)#generate-metagenome-predictions. You may want to use the `--per_sequence_contrib` option as well, which will provide the pathway predictions for each ASV individually rather than how much each ASV contributes to the community-wide pathway abundance.


Cheers,

Gavin
