### ISSUE TITLE
Pathway Abundance per sample vs KO abundance per sample

### ISSUE THREAD

**Issue by Lor-AM** [picrust/picrust2#253]
Hi Gavin ,  For my dataset , I executed picrust2 pipeline using KO ids and reference mapping file as KEGG (command being: 

- pathway_pipeline.py -i pred_metagenome_unstrat.tsv.gz -o KEGG_pathways_out --no_regroup --map /home/****/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv &
- add_descriptions.py -i path_abun_unstrat.tsv.gz --custom_map_table ../KEGG_pathways_info.tsv -o path_abun_unstrat_descrip.tsv.gz & ) .
 I got the output files , KO abundance per sample file and kegg pathway abundance per sample file. I wanted to know for a particular kegg pathway , will the abundance at the pathway level be the sum of the abundances of the individual KOs involved in the pathway? I did a summation of the individual KOs but there is a big difference between the two.
**For example:** for the pathway **ko00720** , the sample 1 in my output file has an abundance of **3689.23529411765** but the sum total of all the KOs for the pathway in the metagenome file is **133966.5**. I am probably missing something here . Could you please explain this to me ? Similar scenario is the case with EC nos. Secondly when I try to map the EC nos for a pathway to the EC nos identified . Some of them are missing . So is there a threshold as to the no of ECs found to ascertain the pathway is present in a metagenome sample or not? Kindly help me out

**Comment by gavinmdouglas** [comment]
Hey @Lor-AM,

No - the KEGG pathway abundance will be the harmonic mean of the abundances of all KOs in the pathway. Only pathways called as present based on MinPath will be present in the output, so it makes sense some are missing, particularly if not all KOs/ECs connected to a pathway are present.

**Comment by Lor-AM** [comment]
Hi Gavin , thank you for the inputs regarding KO abundances at pathway level. So does it mean that if I check the kegg pathway abundance  For example: for the pathway ko00720 , the sample 1 in my output file has an abundance of 3689.23529411765 at the pathway level. I mapped all the KOs belonging to this pathway AND present in my output file and then calculated the harmonic mean of the KO abundances . I got the value of 87.5549770973757 (Which again doesnt match) ....Probably I am missing something here ...Secondly I was checking the mapping file for MetaCyc (picrust2-2.4.2/picrust2/default_files/pathway_mapfiles)...It does map the pathway id to pathway description...but is there a way to map EC nos belonging to a MEtaCyc pathway ID

**Comment by gavinmdouglas** [comment]
My apologies - you're absolutely right that the harmonic mean approach should not apply in this case. It's been a while since I've looked at this and I forgot the difference. We implemented the same pathway abundance inference approach as done in HUMAnN2, and there is a different approach for structured (like MetaCyc pathways, with key and optional enzymes) and unstructured pathways (like the KEGG Pathways, which, at least in the input files we provide, are just lists of genes, with no information about whether they are key or not).

The unstructured pathways (KEGG in this case) are calculated based on sorting the abundance of all reactions/genes in that pathway, and then taking the arithmetic mean of the abundances of genes in the upper second half of that sorted list.

In contrast, for structured pathways (i.e., MetaCyc) the abundances are based on the harmonic mean of the key reactions/genes. There are some other subtleties as well, such as a gap filling (setting the reaction/gene with the lowest abundance to be that of the second-lowest abundance), and including optional reactions to some degree as well (specifically, optional reactions with abundance > harmonic mean based on key reactions alone are included in the calculation too). Last, there can be nested pathways/sub-pathways in the structures, which are computed recursively (i.e., the abundance of a sub-pathway is computed and then its abundance is treated just like that of any other reaction).

Sorry for the confusion, hopefully that clears it up.

Regarding your second point - the ECs are mapped to MetaCyc reactions first actually. You can see the mapping file here: `picrust2/picrust2/default_files/pathway_mapfiles/metacyc_rxn_to_level4ec.tsv`. You can see the regrouped file (i.e., the EC abundances regrouped to RXN abundances) in the intermediate folder if you specified that (e.g., `intermediate/pathways/regrouped_infile.tsv`).


Hopefully that helps!

Gavin

**Comment by Lor-AM** [comment]
Thank you Gavin
