### ISSUE TITLE
COG3512 was eliminated in the latest COG database (2020)

### ISSUE THREAD

**Issue by liaochenlanruo** [picrust/picrust2#279]
I found that COG3512 exists in the result of COG predicted by picrust2 latest version. However, COG3512 was eliminated in the latest COG database (2020), and its members were moved into the other COG that includes Cas2 proteins, COG1343.  Does picrust2 use the latest COG database published in 2020?

please see [COG database update: focus on microbial diversity, model organisms, and widespread pathogens](https://academic.oup.com/nar/article/49/D1/D274/5964069?login=false)

**Comment by gavinmdouglas** [comment]
Hi there,

No the default PICRUSt2 database files are based on the 2014 version of the COG database actually, so it is quite behind. You can see the listing of the databases used in the supplementary materials of our manuscript: https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-020-0548-6/MediaObjects/41587_2020_548_MOESM1_ESM.pdf

This is because the annotations were taken from IMG at the time at the time that I was working on this project.


All the best,

Gavin
