### ISSUE TITLE
"Stopping - no ASV ids overlap between input FASTA and sequence abundance table" despite having exact ASV id matching.

### ISSUE THREAD

**Issue by plowmajo** [picrust/picrust2#292]
Hi there,

I am trying to use PICRUSt2 to functionally annotate some 16s ASV data. I am using an ASV sequence .fasta and an abundance matrix from DADA2. I have adjusted the ASV abundance table to the required format in Rstudio, and I doubled checked this in the terminal:

![Screenshot 2023-01-12 at 3 23 24 PM](https://user-images.githubusercontent.com/122502233/211960938-aa8bc8cb-5acd-4129-bee4-59fe41283115.png)

The ASVs in the .fasta were named using the ASV IDs in 

my abundance table, so they should be exactly the same.

I have attached .zips of my inputs.
[ASV Sequences FINAL.fasta.zip](https://github.com/picrust/picrust2/files/10397785/ASV.Sequences.FINAL.fasta.zip)
[ASV_Biom.zip](https://github.com/picrust/picrust2/files/10397786/ASV_Biom.zip)

Thanks so much!

**Comment by gavinmdouglas** [comment]
Hi @plowmajo,

I think the problem is that it's confused about what the input format of your abundance table is. PICRUSt2 will check for the ".biom" extension and otherwise will assume a tab-delimited table has been input. Since your biom table is in JSON format (for future reference: that's the format of the file you sent, while the screenshot is legacy format) you will need to add ".biom" to the end. In other words, rename it to "ASV.biom" and see if the problem is fixed.


Cheers,

Gavin

**Comment by plowmajo** [comment]
Thanks Gavin, that sorted that problem, however, I've run into another! When I run the pipeline command I get the following:

<img width="1440" alt="Screenshot 2023-01-13 at 9 47 37 AM" src="https://user-images.githubusercontent.com/122502233/212177979-5967ba38-beea-4b58-9a92-8c05ad11a89b.png">

I have tried reinstalling using conda, and am running picrust2-2.5.1. I am running on MacOS Ventura 13.1 (M1 Macbook Air) with 8GB ram.

Thanks again for your help!

**Comment by gavinmdouglas** [comment]
Sorry - just seeing this now. Do there happen to be any spaces in your input file names? It looks like there could be a space in "Functional Characterization" which I think could be causing this problem.
