### ISSUE TITLE
clarification on path_abun_contrib  - contributory bacteria to metabolic profile

### ISSUE THREAD

**Issue by EJS01** [picrust/picrust2#324]
Hi, I have some clarification:

may i know why and how did some taxonomically unknown bacteria (assigned as "NA") have been marked by the PICRUST2 pipelines as metabolically active?

For example, one of my unknown bacteria has been tagged as a contributor to PWY-6167.

I'm hoping for your insight on this one. Thanks!

**Comment by gavinmdouglas** [comment]
Hi @EJS01,

PICRUSt2 doesn't consider taxonomy information, so there could be a few reasons why such bacteria might be annotated.

One reason is that a closely related taxon is in the PICRUSt2 database, but not in the database you used to taxonomically classify the sequences. 

Otherwise, it must share some sequence similarity with a distantly related taxon, which means that it was able to get through the sequence similarity initial check and NSTI cut-off. You could try increasing each of these cut-offs when running the tool to see if that eliminates predictions for these taxa. However, I would recommend just filtering out these taxa from your entire dataset if they cannot be classified at the Kingdom level, as they are likely sources of noise in general.

Last, you should be careful with the wording of 'metabolically active' as even with high-quality whole-genome sequences you can't know whether genes are actually being expressed or not, without additional information.


Cheers,

Gavin
