### ISSUE TITLE
Running picrust on shotgun output from bracken

### ISSUE THREAD

**Issue by hkaspersen** [picrust/picrust2#338]
Dear authors,
I was wondering if picrust2 was solely for 16S data, or if it is possible to run it on Bracken/BIOM outputs from shotgun data as well?
I want to do a simple functional analysis of the identified taxa in the dataset, can this be done with picrust2?

Thanks in advance!

**Comment by R-Wright-1** [comment]
Hello,

If you have shotgun data then I would recommend running something that identifies the functions that are in your reads, rather than predicting based on taxonomy. The simplest tool for this is probably HUMAnN3 (see [here](https://huttenhower.sph.harvard.edu/humann/)), but we also have a tutorial for using MMSeqs2 [here](https://github.com/LangilleLab/microbiome_helper/wiki/Metagenomics-Standard-Operating-Procedure-v3). Also note that if your samples are not human, you may not get such good results with HUMAnN3. 

Best wishes,
Robyn

**Comment by hkaspersen** [comment]
Thank you for the feedback! I'll have a look at MMSeqs2 since I am not working with human samples.
