### ISSUE TITLE
Absolute abundance data for picrust2

### ISSUE THREAD

**Issue by sankadinesh** [picrust/picrust2#340]
Hi there,
How to use absolute abundance data (qPCR) as an input for picrust2 analysis ? 
I am planning to convert ASVs read numbers to absolute abundances. Rarefying the absolute abundances before picrust2 or normalisation of pathways abundance after picrust2 ? Which approach would be correct ?

Thanks and regards,
Dinesh

**Comment by mlangill** [comment]
Hi Dinesh,

How do you plan to convert ASV read depths to absolute abundances? If they
are absolute abundances then I don't think you would need to rarefy or
normalize the data before or after picrust. The interpretation of the
picrust results would be absolute counts of gene families and pathways if
the input is absolute values.

Sincerely,

Morgan Langille

**Comment by sankadinesh** [comment]
Hi Langille,
Thanks for your reply. 

I divide the unrarefied ASV count data by 16s copy numbers (ASV wise) and multiply them with qpcr copy number values (sample wise) to derive absolute abundance. I will skip operon normalization step by picrust2. I am wondering whether I have to do rarefaction at any stage ?

Regards,
Dinesh

**Comment by R-Wright-1** [comment]
Hello,

As Morgan said, I don't think you would need to do rarefaction at any stage. I would, however, recommend that caution be taken when trying to imply absolute abundances from 16S sequencing data due to the many biases that can occur during sequencing. I am closing this here as it is not an issue, but if you wish to discuss this further than you can do so within the [picrust-users Google group](https://groups.google.com/g/picrust-users) (and you may get some others users adding in their own experiences, too).
