### ISSUE TITLE
Subset of Reference 16s sequences aligned poorly to reference sequences

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [picrust/picrust2#353]
Hi,

I randomly sampled a subset of 16s RRNA sequences from the reference sequence fasta file (https://github.com/picrust/picrust2/tree/master/picrust2/default_files/prokaryotic)
/pro_ref/pro_ref.fna.

Then I ran place_seqs on the random subsets.

place_seqs.py -s input_seqs -o output_tree -p 1 --intermediate intermediate_folder

I got the error :
Stopping - all 4201 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).

How can reference sequences be poorly aligned to refererence sequences?

Regards
Abel Tan

**Comment by R-Wright-1** [comment]
Hi Abel,

Could you send the file that contains your subset of 16S sequences please? I wouldn't expect this to happen, but can help troubleshoot if you can send the file.

**Comment by Abelcanc3rhack3r** [comment]
Hi,
The file is here:
[16S_sequences.zip](https://github.com/user-attachments/files/17162134/16S_sequences.zip)

**Comment by R-Wright-1** [comment]
Hi again,

The issue is because the ASVs in the subsetted file have the same names as the reference sequences. When checking the aligned file, the names of the reference sequences are first removed from the aligned sequences for comparison - so in this case, the error doesn't mean that the sequences aligned poorly, but rather that they were no longer in the alignment file because of the naming. I renamed them all with the prefix "copy_" and this step ran fine: `place_seqs.py -s 16S_sequences_rename.fna -o placed_seqs_rename.tre -p 24 --intermediate intermediate_folder_rename`

I've attached the files that I used and created.

Robyn

[16S_sequences_rename.fna.zip](https://github.com/user-attachments/files/17218509/16S_sequences_rename.fna.zip)
[placed_seqs_rename.tre.zip](https://github.com/user-attachments/files/17218510/placed_seqs_rename.tre.zip)
