### ISSUE TITLE
Not getting the pred_metagenome_strat.tsv

### ISSUE THREAD

**Issue by misazaa** [picrust/picrust2#38]
Hi!

I'm running the tutorial "CBW 2018 PICRUSt2 Tutorial" with the data you provided and after running the hidden-state prediction step, when I plot the NSTI values in RStudio, I get a plot very different from yours, there are more than one outliers. Moreover, when I run the metagenome pipeline code:
metagenome_pipeline.py -i input_files/ASV_abun.tsv -f EC_predicted.tsv -m 16S_predicted.tsv -p 4
the tutorial says that I should get as output 4 files, but I'm only getting 3, there's no output called pred_metagenome_strat.tsv.

I also tried running the line code of the tutorial with my own data (an ASV table and a FASTA file) and I get the same problem, no pred_metagenome_strat.tsv file

Any ideas why?

Thanks in advance!!

Camila

**Comment by gavinmdouglas** [comment]
Hey there,

That tutorial was based on PICRUSt v2.0.0-b.2 - there have been many changes since then, including to the reference database used, which is why you might see more outliers for instance. In addition, stratified metagenomes are no longer output by default since this can take a lot of memory and CPU time to generate depending on how many sequences you have. You can see a description of the latest versions of the PICRUSt2 scripts here: https://github.com/picrust/picrust2/wiki/Workflow <https://github.com/picrust/picrust2/wiki/Workflow>

To get stratified metagenomes you can use the option “— strat_out” with metagenome_pipeline.py. If you run into issues running this command you can try combining rare ASVs into the same category by setting the —min_reads and —min_samples options to be integers greater than 1.


Hopefully that helps!

Gavin
