### ISSUE TITLE
`placement_tools/` directory missing

### ISSUE THREAD

**Issue by JCSzamosi** [picrust/picrust2#50]
I have just cloned this repository and am trying to install the prerequisites, but the `placement_tools/` directory that is supposed to contain the epa-ng and gappa source code is missing.

**Comment by gavinmdouglas** [comment]
You'll need to download the source tarball specified in the install instructions: https://github.com/picrust/picrust2/wiki/Installation#after-installing-these-pre-requisites-download-the-source

The latest version doesn't have this folder since the pre-requisites are now available on bioconda. Some users are reporting issues with the latest version of EPA-NG though so I'm pointing to the previous version (2.0.3-b) still in the install instructions.

Thanks,

Gavin

**Comment by JCSzamosi** [comment]
Ah! The instructions specifically say to download that tarball _after_ installing the prerequisites, which is quite confusing if it contains the prerequisites.

Thank you!

**Comment by gavinmdouglas** [comment]
Yes I see that's really confusing; I'll fix that. Thanks for pointing that out.
