### ISSUE TITLE
Which reference files to use for Picrust2 in Q2

### ISSUE THREAD

**Issue by tarunaaggarwal** [picrust/picrust2#51]
Hi @gavinmdouglas - Really glad to see the release of Picrust2! Thank you so much! I have a quick question about the reference files to use to run Picrust2 with Q2. I have a rooted and an unrooted tree that I created from Qiime2 already but looks like I need to place my ASVs onto a Picrust2 reference tree instead. Can you please clarify where these Picrust2 reference tree files are located? Should I use the same reference tree file that comes with the tutorial you have posted on Github? Please let me know. Thank you so much! -Taruna

**Comment by gavinmdouglas** [comment]
Hi there,

Thanks for your interest!

You need to use the same reference tree and alignment as were used in the tutorial. I.e. ```reference.fna.qza``` and ```reference.tre.qza```. 

If you have further usage questions you may want to search this google group first since others may have asked the same question: https://groups.google.com/forum/#!forum/picrust-users


Best,

Gavin
