### ISSUE TITLE
genome trait prediction output for qiime2?

### ISSUE THREAD

**Issue by mortonjt** [picrust/picrust2#60]
Very excited to be testing this out!

Right now, I'm trying to perform something similar to [genome_prediction.py](http://picrust.github.io/picrust/tutorials/genome_prediction.html#genome-prediction-tutorial), but I don't see a way to do this with the current qiime2 picrust workflow.

Will there be plans on including this file?  This can be especially useful when comparing 16S hits on a phylogenetic tree for instance.

**Comment by gavinmdouglas** [comment]
Thanks for checking out picrust2! The q2-picrust2 plugin has limited functionality and doesn't give access to the intermediate files. However, you can get access to all the intermediate files and more options if you use the standalone version.

Just to be clear - the genome predictions steps are run for each dataset with PICRUSt2 rather than relying on predictions for a set of reference 16S sequences. This process has been streamlined and you just need to point to the reference files to use (see [here](https://github.com/picrust/picrust2/wiki/Sequence-placement#using-custom-reference-files) if you want to use a custom reference database).
