### ISSUE TITLE
PiCrust2 categorize_by_function.py

### ISSUE THREAD

**Issue by kris-budd** [picrust/picrust2#65]
Hi Gavin, 

I'm just wondering if there is a categorize_by_function.py script within PiCrust2 (Specifically within the QIIME2 plugin) like in the original PiCrust in order to collapse the pathways into higher level of the pathway hierarchy? 

I've successfully produced the KO_metagenome.qza, EC_metagenome.qza and the pathway_abundance.qza and have also been able to export and convert them biom > .spf using your Microbiome helper but I'm still only able to run and visualize on individual KO instead of functional groups. 

Any thoughts?

**Comment by gavinmdouglas** [comment]
The equivalent step in PICRUSt2 is to infer pathway abundances based on gene family abundances (EC number abundances by default). The pathway level predictions are focused on the MetaCyc pathways by default with PICRUSt2. This is mainly because KEGG is closed-source now. However, you can use custom pathway mapping files with ```pathway_pipeline.py``` if you have a mapping file for KEGG pathway ids to KEGG orthologs you would like to use.


Gavin
