### ISSUE TITLE
Difference in results between q2-picrust2 and picrust2_pipeline.py? 

### ISSUE THREAD

**Issue by AbhishakeL** [picrust/picrust2#66]
I have run the same biom file and representative sequences with both the qiime2 plugin of picrust2 and the picrust2_pipeline.py program, and have found around 600 KOs to be present/absent in one v/s the other. Also the KOs which are present in both the results show different abundance values. Can this difference be attributed to SEPP v/s EPA-NG?

**Comment by gavinmdouglas** [comment]
Hey @AbhishakeL,

Thanks for reporting this observation.

Just to check - did you run the same version of PICRUSt2 each time?

The predictions wont be identical when the ASV placements differ, so it's normal to see differing numbers of KOs present/absent between the two pipelines. However, I haven't seen that many presence/absence differences with test datasets. How many input ASVs did you input?

**Comment by AbhishakeL** [comment]
Hello @gavinmdouglas ,
So far as versions are concerned,
`$qiime picrust2 --version`
`picrust2 version 0.0.0 `
And
`$picrust2_pipeline.py -v`
`picrust2_pipeline.py 2.1.0-b`

Also, the biom contained 4050 ASVs.
Please do tell if you need any other information. Actually I am trying to pin-point the source of the difference.

**Comment by gavinmdouglas** [comment]
Ok thanks. The easiest way to figure out what's causing the difference would be to run the same version of PICRUSt2 by hand on a tree produced by SEPP compared to the default EPA-NG pipeline. There will be numerous version and minor functionality differences otherwise if you're comparing the q2-picrust2 output to the latest picrust2 (v2.1.0-b isn't compatible with the q2-plugin so you must be using an earlier version for that pipeline).
