### ISSUE TITLE
pathway_pipeline.py not found

### ISSUE THREAD

**Issue by adityabandla** [picrust/picrust2#71]
I installed picrust2 using the conda method. All steps run fine except the pathway abundance step. I get the error that pathway_pipeline.py not found although pytests doesnt report any error

**Comment by gavinmdouglas** [comment]
There are tests that check whether pathway_pipeline.py can be run in the pytest so the pytests shouldn't have completed successfully. Did you run pytest after downloading the source code? Running pytest wont do anything unless you run it on the test scripts that are in the github repo. 

Is it possible that you already had an earlier version of PICRUSt2 installed in the conda environment you're using? I re-named run_minpath.py to be pathway_pipeline.py in a recent version which is why it might only fail at that step.

Gavin

**Comment by adityabandla** [comment]
Hi Gavin

I think it was just the name of the file that was causing the issue. I was following the tutorial and perhaps didn't have the latest version of PICRUST2

run_minpath.py worked
