### ISSUE TITLE
Picrust2 and STAMP compability

### ISSUE THREAD

**Issue by OnlyHigh** [picrust/picrust2#78]
Hi, 
I haven't been able to integrate picrust2 with STAMP in order to plot the picrust2 results, 
I have been trying to follow this tutorial (https://github.com/LangilleLab/microbiome_helper/wiki/PICRUSt-tutorial) but... I haven't succeed, 

Any recommendations? or advice? or new tutorial?

**Comment by gavinmdouglas** [comment]
Hi @OnlyHigh,

That tutorial is for PICRUSt1 and there isn't a similar tutorial for PICRUSt2 yet. However, I think the unstratified tables should work in STAMP by default since it just requires tab-delimited input files.

**Comment by mlangill** [comment]
Yes, indeed the unstratified tables will work in STAMP. You can check out this tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial
-------------------------------------------
Dr. Morgan Langille
Canada Research Chair in Human Microbiomics
Assistant Professor
Department of Pharmacology, Dalhousie University
http://morganlangille.com<http://morganlangille.com/>

Director
Integrated Microbiome Resource (IMR)
http://cgeb-imr.ca<http://cgeb-imr.ca/>


On Thu, May 2, 2019 at 5:39 AM Gavin Douglas <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @OnlyHigh<https://github.com/OnlyHigh>,

That tutorial is for PICRUSt1 and there isn't a similar tutorial for PICRUSt2 yet. However, I think the unstratified tables should work in STAMP by default since it just requires tab-delimited input files.

**Comment by OnlyHigh** [comment]
Hi @gavinmdouglas @mlangill, 
I understand, it's working perfectly, 
thanks @mlangill for the tutorial!

**Comment by Sirbius** [comment]
Hi there,

I'm trying to load the unstratified tables obtained through picrust2 but I do not get which window should be selected when creating the STAMP profile. It is expecting a biom file, mothur, MG-RAST ecc.. but not un unstratified tsv file.
Indeed then I got errors, especially when loading the metadata tsv file.
I see that @OnlyHigh did not have issues, but it would be great to know how he did.
Thanks

**Comment by OnlyHigh** [comment]
Hey @Sirbius 
if I remember correctly I used "path_abun_unstrat.tsv" as input file to do the STAMP analyses, but if the format is the issue, I think you can convert the format tsv to biom 
cheers,
